### ISSUE TITLE
get_devices doesn't work for de server

### ISSUE THREAD

**Issue by dominikkarall** [Squachen/micloud#7]
Hi,

get_devices doesn't work any more for de servers. Could you please fix this, see here:
https://github.com/al-one/hass-xiaomi-miot/commit/e0d8d6bc53b1fec07c8e4da51497583ee9b0dd04#diff-6b1581eb1057820910622bad460b6bc37b06927e039292a08d4cff837c87f6d8

The request needs to be rc4 encrypted as far as I can see.

**Comment by Squachen** [comment]
I'll try to implement this asap. See: https://github.com/Squachen/micloud/issues/4#issuecomment-1004237727
